version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo repo --- $REPOSITORY_URI
      - docker --version
      - aws --version
      - echo $(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo $(docker login --username AWS --password-stdin $REPOSITORY_URI)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Writing image definitions file...
      - printf '[{"name":"test/schedule-task","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - aws s3 cp imagedefinitions.json s3://scheduletaskbucket/imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
